#+title: Testing Cosmological Isotropy through a Cosmographic approach
#+STARTUP: showall


This repo contains all the code for the paper referenced paper.

* Table of Contents :toc:
- [[#how-to-run][How to run]]
- [[#dependencies][Dependencies]]
- [[#Main File][Where to start]]
* How to run

Just download all the files inside the repo or alternatively use git clone.

#+begin_src
git clone https://github.com/leoriohub/cosmographic_analysis.git
#+end_src

The code must be ran from main.ipynb notebook.

* Dependencies

There are some python libraries needed, they are all available on pip.
#+begin_src
pip install scipy healpy numpy pandas multiprocessing
#+end_src

* Main file

The code should be run from the jupyter notebook called *main.ipynb*. In this file, one can generate Hubble-maps and q-maps by calling the custom functions defined in all the /.py/ modules.

This file is properly commented so one can understand what every custom function is doing in general. For details on one particular function, refer to the corresponding /.py/ module.